### ISSUE TITLE
Unable to add custom constraint file for the first time because the constraint directory is not automatically created 

### ISSUE THREAD

**Issue by natalieagus** [alchitry/Alchitry-Labs-V2#29]
Alchitry Lab version: 2.0.16-BETA 

I wanted to add the IO constraint (seems like it's not yet part of the library). I added it from the GUI:

<img width="774" alt="image" src="https://github.com/user-attachments/assets/731e2c01-cdeb-4aea-b87e-f209b676f88e">

However, it seems to not be able to find the path where the file is supposed to be created, because it does not create the `constraint` directory when it does not exist yet. 

<img width="1038" alt="image" src="https://github.com/user-attachments/assets/fcc0bcbc-4a02-49d6-818d-9125bef03402">

I had to manually created the constraint folder in the project directory, quit Alchitry, and then retry to successfully created a custom constraint file.

**Comment by alchitry** [comment]
I'll look into having it make the directory when adding constraints, but just curious, was this from an official install or did you build from source? I think the constraint folder may not be created from builds from source because the empty constraint folder isn't present in the repository (git doesn't track empty folders).

**Comment by natalieagus** [comment]
Both. Official Apple Silicon install is also unable to create custom constraints without the directory being created first: 

<img width="1409" alt="image" src="https://github.com/user-attachments/assets/2c3bc739-5fa6-4135-84af-759c5310823a">

I found the official `io.acf` from components. After adding that, it is still unable to add custom constraints because of the same issue:

<img width="685" alt="image" src="https://github.com/user-attachments/assets/de7dc23b-c1a7-4f29-a0da-ef364551a16f">


One small bug: When I click "OK", and then attempt to create again, there's no window pop up anymore. I have to restart Alchitry Labs. 

<img width="566" alt="image" src="https://github.com/user-attachments/assets/f837f1ac-d222-4c2f-a7ac-3ee8a4e8608c">

**Comment by alchitry** [comment]
That style of error dialog is from an uncaught exception (aka crash). I'm surprised the whole thing didn't close after you clicked OK.

I added a catch for errors when creating files as well as creating the parent directory to begin with.
