### ISSUE TITLE
Can't open AlchitryLabV2 2.0.5 on macOS (Sonoma 14.1, M2 Macbook Air)

### ISSUE THREAD

**Issue by natalieagus** [alchitry/Alchitry-Labs-V2#3]
Hello! I downloaded the latest AlchitryLabV2 from your [link here](https://new.alchitry.com/Alchitry-Labs-V2/download.html), and after following the instructions to control click and open the app, there's the macOS security prompt and I clicked open. 

However, nothing pops up afterwards. 

The exact release version is: [alchitry-labs-2.0.5-mac-aarch64.zip](https://github.com/alchitry/Alchitry-Labs-V2/releases/download/2.0.5/alchitry-labs-2.0.5-mac-aarch64.zip). I tried finding crash logs but unable to find any. Is there any tips for troubleshooting? 

I am able to open all earlier versions on my mac (2.0.4, 2.0.3, 2.0.2) and successfully loaded various .bin files to my Alchitry Au. This issue only arises for version 2.0.5. Thank you.

**Comment by alchitry** [comment]
Thanks for submitting the issue. Turns out I missed renaming the package so this was an issue on all systems.

It'll be fixed in 2.0.6.
