### ISSUE TITLE
next-try referencing to /opt/homebrew directory during Yosys build [Mac]

### ISSUE THREAD

**Issue by Zephyr1371** [alchitry/Alchitry-Labs-V2#5]
Hi, Fantastic project you are working on. I have just run the 2.09 build on an M1 Mac. The build was using one of the basic examples (or very similar). I switched to the Yosys build and it ran until step - 3.50. Executing JSON Backend - where it tried to call nextpnr using a /opt/homebrew directory. I assume this just hasn't been switched over to reference an internal package directory:

> 3.48. Printing statistics.
> 
> === MI_alchitryTop ===
>
>   Number of wires:                 11
>   Number of wire bits:             24
>   Number of public wires:          11
>   Number of public wire bits:      24
>   Number of memories:               0
>   Number of memory bits:            0
>   Number of processes:              0
>   Number of cells:                  0
>
> 3.49. Executing CHECK pass (checking for obvious problems).
> Checking module MI_alchitryTop...
> Found and reported 0 problems.
>
> 3.50. Executing JSON backend.

....

> Yosys 0.34+55 (git sha1 xxxxxxxx  clang 15.0.0 -fPIC -Os)
> Time spent: 98% 15x read_verilog (4 sec), 0% 1x synth_ice40 (0 sec), ...
> Starting nextpnr...
> dyld[72543]: Library not loaded: /opt/homebrew/opt/zstd/lib/libzstd.1.dylib

....

> Nextpnr exited with status: 134

**Comment by alchitry** [comment]
Added the necessary libraries to the install for ARM based Macs. Builds 2.0.11 and later will have them.
